insert into food_items (name, calories, protein, carbs, fat) values ('Pastry - Choclate Baked', 449, 74, 88, 85);
insert into food_items (name, calories, protein, carbs, fat) values ('Cake - Dulce De Leche', 285, 80, 87, 16);
insert into food_items (name, calories, protein, carbs, fat) values ('V8 - Vegetable Cocktail', 401, 26, 68, 33);
insert into food_items (name, calories, protein, carbs, fat) values ('Wine - Casablanca Valley', 227, 87, 5, 44);
insert into food_items (name, calories, protein, carbs, fat) values ('English Muffin', 174, 90, 87, 25);
insert into food_items (name, calories, protein, carbs, fat) values ('Chivas Regal - 12 Year Old', 384, 66, 96, 44);
insert into food_items (name, calories, protein, carbs, fat) values ('Longos - Grilled Veg Sandwiches', 145, 84, 23, 76);
insert into food_items (name, calories, protein, carbs, fat) values ('Bread - Raisin', 300, 50, 43, 32);
insert into food_items (name, calories, protein, carbs, fat) values ('Soy Protein', 464, 50, 85, 70);
insert into food_items (name, calories, protein, carbs, fat) values ('Rambutan', 133, 15, 13, 35);
insert into food_items (name, calories, protein, carbs, fat) values ('Lentils - Red, Dry', 294, 40, 83, 18);
insert into food_items (name, calories, protein, carbs, fat) values ('Kolrabi', 79, 63, 95, 96);
insert into food_items (name, calories, protein, carbs, fat) values ('Egg Patty Fried', 355, 100, 63, 4);
insert into food_items (name, calories, protein, carbs, fat) values ('Wine - Gato Negro Cabernet', 359, 24, 33, 15);
insert into food_items (name, calories, protein, carbs, fat) values ('Shallots', 268, 6, 23, 64);
insert into food_items (name, calories, protein, carbs, fat) values ('Squash - Guords', 390, 82, 21, 26);
insert into food_items (name, calories, protein, carbs, fat) values ('Liqueur - Melon', 478, 39, 89, 41);
insert into food_items (name, calories, protein, carbs, fat) values ('Isomalt', 355, 32, 67, 90);
insert into food_items (name, calories, protein, carbs, fat) values ('Soup - Cream Of Potato / Leek', 479, 16, 65, 28);
insert into food_items (name, calories, protein, carbs, fat) values ('Sauce - Thousand Island', 279, 85, 4, 99);
insert into food_items (name, calories, protein, carbs, fat) values ('Cookie - Oatmeal', 406, 41, 11, 48);
insert into food_items (name, calories, protein, carbs, fat) values ('Juice - Clam, 46 Oz', 201, 29, 73, 50);
insert into food_items (name, calories, protein, carbs, fat) values ('Food Colouring - Orange', 84, 80, 46, 89);
insert into food_items (name, calories, protein, carbs, fat) values ('Cheese - Brie', 105, 94, 18, 29);
insert into food_items (name, calories, protein, carbs, fat) values ('Milk - 1%', 384, 78, 19, 41);
insert into food_items (name, calories, protein, carbs, fat) values ('Bread - Kimel Stick Poly', 297, 15, 100, 35);
insert into food_items (name, calories, protein, carbs, fat) values ('Kaffir Lime Leaves', 135, 85, 4, 57);
insert into food_items (name, calories, protein, carbs, fat) values ('Mushroom - Morel Frozen', 362, 38, 18, 89);
insert into food_items (name, calories, protein, carbs, fat) values ('Turnip - Mini', 191, 50, 17, 97);
insert into food_items (name, calories, protein, carbs, fat) values ('Tomatoes - Orange', 114, 97, 14, 97);
insert into food_items (name, calories, protein, carbs, fat) values ('Watercress', 464, 37, 16, 42);
insert into food_items (name, calories, protein, carbs, fat) values ('Puff Pastry - Sheets', 436, 67, 39, 86);
insert into food_items (name, calories, protein, carbs, fat) values ('Basil - Seedlings Cookstown', 245, 74, 62, 24);
insert into food_items (name, calories, protein, carbs, fat) values ('Tea - Orange Pekoe', 497, 93, 27, 31);
insert into food_items (name, calories, protein, carbs, fat) values ('Tequila - Sauza Silver', 487, 92, 85, 18);
insert into food_items (name, calories, protein, carbs, fat) values ('Sprouts - Peppercress', 408, 37, 54, 70);
insert into food_items (name, calories, protein, carbs, fat) values ('Stainless Steel Cleaner Vision', 216, 64, 53, 4);
insert into food_items (name, calories, protein, carbs, fat) values ('Wine - Sawmill Creek Autumn', 205, 96, 66, 94);
insert into food_items (name, calories, protein, carbs, fat) values ('Wine - Dubouef Macon - Villages', 60, 36, 16, 87);
insert into food_items (name, calories, protein, carbs, fat) values ('Dawn Professionl Pot And Pan', 178, 7, 28, 63);
insert into food_items (name, calories, protein, carbs, fat) values ('Oranges', 242, 79, 11, 92);
insert into food_items (name, calories, protein, carbs, fat) values ('Sage - Fresh', 86, 37, 4, 23);
insert into food_items (name, calories, protein, carbs, fat) values ('Steel Wool S.o.s', 360, 72, 42, 7);
insert into food_items (name, calories, protein, carbs, fat) values ('Versatainer Nc - 888', 471, 36, 39, 26);
insert into food_items (name, calories, protein, carbs, fat) values ('Cheese - Gorgonzola', 205, 93, 42, 44);
insert into food_items (name, calories, protein, carbs, fat) values ('Cheese - Mix', 215, 6, 52, 23);
insert into food_items (name, calories, protein, carbs, fat) values ('Energy Drink - Franks Pineapple', 168, 75, 87, 24);
insert into food_items (name, calories, protein, carbs, fat) values ('Puree - Passion Fruit', 168, 26, 8, 6);
insert into food_items (name, calories, protein, carbs, fat) values ('Flour - Buckwheat, Dark', 482, 41, 22, 95);
insert into food_items (name, calories, protein, carbs, fat) values ('Eggplant - Asian', 76, 17, 21, 7);
